#!/usr/bin/python

import os
import struct
import array
import time as _time
from fcntl import ioctl

from ccmqtt import rawjoystick
from ccmqtt.rawjoystick import RawJoystick

def button_callback(joystick: RawJoystick, button: int, value: int):
    print("{} - B:{}:{}".format(joystick.path, button, value))

def axis_callback(joystick: RawJoystick, axis: int, value: int):
    print("{} - A:{}:{}".format(joystick.path, axis, value))

def main_loop():

    rawjoystick.list_joysticks()

    joysticks = []

    joysticks.append( RawJoystick("/dev/input/js0") )
    #joysticks.append( RawJoystick("/dev/input/js1") )

    for joystick in joysticks:
        joystick.add_axis_listener(axis_callback)
        joystick.add_button_listener(button_callback)

    while True:

        for joystick in joysticks:
            joystick.update_blocking()


main_loop()
