[package]
name = "libcircuitcubes"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
# serde.workspace = true
# serde_json.workspace = true


# anyhow.workspace = true
# btleplug.workspace = true
# tokio.workspace = true
# futures.workspace = true
# pretty_env_logger.workspace = true
# tokio-stream.workspace = true
# uuid.workspace = true

btleplug = { version = "0.11", features = ["serde"] }
tokio = { version = "1.44.2", features = ["macros", "rt", "rt-multi-thread"] }
futures = "0.3.31"
anyhow = "1"
# pretty_env_logger = "0.5.0"
tokio-stream = { version = "0.1.17", features = ["sync"] }
uuid = "1.16.0"

[lib]
name = "libcircuitcubes"
path = "src/lib.rs"
test = false
doctest = false
bench = false